# Name of site (displayed in the header)
name: Personal list of resources for AI, programming, math and more

# Site title
title: Bookmarks

# Short bio or description (displayed in the header)
description: Personal list of resources for AI, programming, math and more

plugins:
  - jemoji

theme: jekyll-theme-cayman
